name: Deploy Angular Frontend

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build and Push Docker Image to ECR
      run: |
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        
        docker build -t $ECR_URI:latest .
        docker push $ECR_URI:latest

    - name: Copy SSH Keys to Runner
      run: |
        echo "${{ secrets.JUMP_SSH_KEY }}" > jump.pem
        chmod 600 jump.pem
        

    - name: Deploy on Private EC2
      run: |
        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}

        ssh -o StrictHostKeyChecking=no -i jump.pem ubuntu@${{ secrets.JUMP_HOST }} << EOF
          ssh -o StrictHostKeyChecking=no -i /home/ubuntu/django-keypair.pem ubuntu@${{ secrets.PRIVATE_HOST }} << INNER_EOF
            echo "Logging into ECR..."
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_URI

            echo "Stopping and removing existing container (if running)..."
            docker stop django-backend-container || true
            docker rm django-backend-container || true

            echo "Pulling the latest image from ECR..."
            docker pull $ECR_URI:latest

            echo "Running the new container..."
            docker run -d --name django-backend-container -p 8000:8000 $ECR_URI:latest
          
